### ISSUE TITLE
extract method just for one java class/method

### ISSUE THREAD

**Issue by zhipeng-cai** [mahnooshshd/extract_method#3]
hello, i wonder if i can use your algorithm to extract method just for one single java class/method.

Because i see your algorithm is designed for a java project, and when running the algorithm for a single java class, i am not sure weather it will take the information(data/call dependency) from other java class into account. If the algorithm need information from other class, maybe it is not suitable to extract method for a single java class/method?

**Comment by m-zakeri** [comment]
Dear @zhipeng-cai,
Typically, no class is used in isolation. A better approach, I think, is to use the mock and stub objects to make your class ready for use in isolation. It is because at least the call graph construction used in our approach requires compilable Java code. 

Such behavior is also observed in other Java Extract method refactoring tools. For example, [JDeodorant](https://github.com/tsantalis/JDeodorant) requires all dependencies to extract object-based slices and the given project must be compilable. 

I hope this would be helpful.
